### ISSUE TITLE
Pending 1.1.1 update into Cocoapods 

### ISSUE THREAD

**Issue by manusalinas-mx** [getlarky/nudgeGeo#2]
Hi there!

We are consuming **nudgeGeo 1.0.0** in our project (Sharetec) via **cocoapods**.  We noticed a new library update has been released based on your documentation [Here](https://support.larky.com/hc/en-us/articles/9782896787735-nudge-Base-nudge-Geo-Code-Library-for-iOS-Integration-Guide)

- **Version 1.1.1 already contains PrivacyInfo manifest file which will be required by Apple starting May 1, 2024**

<img width="857" alt="Screenshot 2024-04-24 at 9 24 33 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/850dc657-0a90-4b63-82a5-41e562cc75e5">

### However, when we tried to update the pod file we are getting the following error:

<img width="1009" alt="Screenshot 2024-04-24 at 9 26 25 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/28de30a1-7936-4e14-8ae8-3dec625da021">

### Then we verified on cocoapods and we realized that there is no version 1.1.1 there yet

<img width="1262" alt="Screenshot 2024-04-24 at 9 09 39 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/849d93c0-cd35-4ef5-9873-41bf0c160f2f">

<img width="1494" alt="Screenshot 2024-04-24 at 9 10 23 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/7f29d093-3b0e-4de7-95ef-1bf14422c1b3">

- ### **So we would like to ask you if the new v1.1.1  pod is coming soon to cocoapods?**

Thanks

cc @kschaldenbrand @FCosse @connorlarky @d-hauk

**Comment by connorlarky** [comment]
Hi @manuelsalinas-mx ,

Sorry for the confusion, we recently moved the nudgeGeo and nudgeBase libraries to be private pods. Please add this line to your Podfile where you list the sources and let me know if that has resolved your issue

`source 'https://github.com/getlarky/nudgePods.git'`

Best,

Connor

**Comment by manusalinas-mx** [comment]
> Hi @manuelsalinas-mx ,
> 
> Sorry for the confusion, we recently moved the nudgeGeo and nudgeBase libraries to be private pods. Please add this line to your Podfile where you list the sources and let me know if that has resolved your issue
> 
> `source 'https://github.com/getlarky/nudgePods.git'`
> 
> Best,
> 
> Connor

Thanks for quick reply.  Sure! let me try that : )

**Comment by manusalinas-mx** [comment]
> Hi @manuelsalinas-mx ,
> 
> Sorry for the confusion, we recently moved the nudgeGeo and nudgeBase libraries to be private pods. Please add this line to your Podfile where you list the sources and let me know if that has resolved your issue
> 
> `source 'https://github.com/getlarky/nudgePods.git'`
> 
> Best,

Hi @connorlarky  
Me again 

### I added de source 'https://github.com/getlarky/nudgePods.git' but I issue persists 

### Podfile

![image](https://github.com/getlarky/nudgeGeo/assets/110424672/97b2c2a2-dbf8-44a2-981c-9b2328517565)

### Terminal 

<img width="979" alt="Screenshot_2024-04-24_at_10_46_42 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/36edeb03-12b9-493b-90e7-43f3571d3eca">


### Using  pod repo add

<img width="976" alt="Screenshot_2024-04-24_at_11_08_35 AM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/a4ed9d92-3af9-4128-8981-9742802ca867">

**Comment by connorlarky** [comment]
Hi @manuelsalinas-mx 

Have you tried using the `pod update` command in the command line?

Best,

Connor

**Comment by manusalinas-mx** [comment]
> Hi @manuelsalinas-mx
> 
> Have you tried using the `pod update` command in the command line?
> 
> Best,
> 
> Connor

@connorlarky Yeap! 
But same issue 

<img width="985" alt="Window_and_mobile-banking-ios_—_-zsh_—_153×31" src="https://github.com/getlarky/nudgeGeo/assets/110424672/b728998b-58ad-4d88-80ad-aa5f879be3ae">

**Comment by connorlarky** [comment]
Hello @manuelsalinas-mx 

Thank you for trying that. I think the visibility of the repo is causing issues so I changed the repo the nudgeGeo pod is being hosted to public. Can you try to install the pod again and let me know if the issue is resolved?

Best,

Connor

**Comment by manusalinas-mx** [comment]
> Hello @manuelsalinas-mx
> 
> Thank you for trying that. I think the visibility of the repo is causing issues so I changed the repo the nudgeGeo pod is being hosted to public. Can you try to install the pod again and let me know if the issue is resolved?
> 
> Best,
> 
> Connor

### @connorlarky sure! let me try and thanks for your support.  Testing again ...

**Comment by manusalinas-mx** [comment]
> Hello @manuelsalinas-mx
> 
> Thank you for trying that. I think the visibility of the repo is causing issues so I changed the repo the nudgeGeo pod is being hosted to public. Can you try to install the pod again and let me know if the issue is resolved?
> 
> Best,
> 
> Connor

@connorlarky 

### Not sure if you have any idea for issue I got this time

<img width="1015" alt="Window_and_mobile-banking-ios_—_-zsh_—_152×38" src="https://github.com/getlarky/nudgeGeo/assets/110424672/aeb0a7b1-5796-4e16-acb4-c171c55c3d85">


### Changes on Podfile 

```
# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# THIS IS NEW FOR nudgeGeo <<<<<<<<<<==============
source 'https://github.com/getlarky/nudgePods.git' 

# The reason we are including all the GoogleUtilities dependencies:
#  https://stackoverflow.com/questions/68671129/multiple-commands-produce-for-all-cocoa-pods-when-archived

def test_target_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
pod 'SPConfetti'
  pod 'FirebaseAnalytics', '~> 9'
  pod 'FirebaseMessaging', '~> 9'
  pod 'FirebaseCrashlytics', '~> 9'
  pod 'Moya', '~> 15'
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/UserDefaults'
  pod 'GoogleUtilities/Reachability'
  pod 'ReactiveCocoa', '~> 12.0'
  pod 'SwiftyBeaver', '~> 1.9.5'
  pod 'IQKeyboardManagerSwift', '~> 6.5.9'
  pod 'KeychainSwift', '~> 20.0.0'
  pod 'MaterialComponents/TextFields', '~> 124.2.0'
  pod 'SwiftyJSON'
  pod 'nudgeGeo', '~> 1.1.1'   # THIS IS NEW FOR nudgeGeo <<<<<<<<<<==============
end
```

**Comment by connorlarky** [comment]
Hi @manuelsalinas-mx 

I believe that the Analytics dependency in reference is hosted by cocoapods, can you add this line next to where you included the source line for nudgePods? 
`source 'https://cdn.cocoapods.org/'`

Also when I was looking into this, I noticed that when going to the [cocoapods website](https://cocoapods.org/) I was getting an Internal Server Error page so I am not sure if that would effect downloading pods that are hosted by cocoapods publicly. 
<img width="634" alt="Screenshot 2024-04-24 at 3 24 21 PM" src="https://github.com/getlarky/nudgeGeo/assets/79119090/3eee47b3-80b1-4df4-803a-cd2fd26d731b">

Best,

Connor

**Comment by manusalinas-mx** [comment]
> Hi @manuelsalinas-mx
> 
> I believe that the Analytics dependency in reference is hosted by cocoapods, can you add this line next to where you included the source line for nudgePods? `source 'https://cdn.cocoapods.org/'`
> 
> Also when I was looking into this, I noticed that when going to the [cocoapods website](https://cocoapods.org/) I was getting an Internal Server Error page so I am not sure if that would effect downloading pods that are hosted by cocoapods publicly. <img alt="Screenshot 2024-04-24 at 3 24 21 PM" width="634" src="https://private-user-images.githubusercontent.com/79119090/325355276-3eee47b3-80b1-4df4-803a-cd2fd26d731b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODc3MjcsIm5iZiI6MTcxMzk4NzQyNywicGF0aCI6Ii83OTExOTA5MC8zMjUzNTUyNzYtM2VlZTQ3YjMtODBiMS00ZGY0LTgwM2EtY2QyZmQyNmQ3MzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5MzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYzA1OGQwNzRmMDc2ODNhOTM3YTY3NjA4MmE0ODg3ZDQ2YTRmOGY2ZDBiMjE2Y2E1ZTg0MDYwNTlmZDA1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oyRNw3ZuCg9mkqAhnk5XsUU_nAr4MVVwHYn-2Pk09Q">
> 
> Best,
> 
> Connor

### @connorlarky  you’re right. I got same error from cocoapods website.  Let me add the new source line 😃 and I’ll let you know any result 

by the way. Is it normal that new 1.1.1 version is not visible when you search it on cocoapods site?  (I did this search early morning) 

<img width="1262" alt="image" src="https://github.com/getlarky/nudgeGeo/assets/110424672/5bee1351-d9ca-407a-9c39-f688c91f581e">

**Comment by manusalinas-mx** [comment]
### Hey @connorlarky finally works!

### Terminal

<img width="1159" alt="mobile-banking-ios_—_-zsh_—_165×47" src="https://github.com/getlarky/nudgeGeo/assets/110424672/02555d0e-beb3-43f5-88a8-f754dc5722ec">


### Podfile

<img width="535" alt="Screenshot 2024-04-24 at 2 12 03 PM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/90aa3b34-2d16-4536-ba39-db3dddf10cfc">



### Podfile lock 

<img width="594" alt="Screenshot 2024-04-24 at 2 12 17 PM" src="https://github.com/getlarky/nudgeGeo/assets/110424672/1d495f59-c590-4597-bed0-9124b396b075">


### I'm really thankful for all your support 💯

**Comment by connorlarky** [comment]
You're Welcome! Glad it is working for you now.
